module.exports = {
  reporters: [
    'default',
    [
      'jest-html-reporters',
      {
        filename: 'report.html',
        outputPath: './test-results/jest_html_report',
        pageTitle: 'Library Management Client Test Report',
        expand: true,
        openReport: true,
        includeConsoleLog: true,
        darkTheme: true,
        useInlineStyles: true,
        customInfos: [
          {
            title: 'Project',
            value: 'Library Management System',
          },
          {
            title: 'Component',
            value: 'Client',
          },
          {
            title: 'Date',
            value: '2025-06-12 16:57:09',
          },
          {
            title: 'Generated by',
            value: '6ebeng',
          },
        ],
      },
    ],
  ],
};
