version: '3.8'
services:
  mongo:
    container_name: mongo
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
      - ./server/scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - MONGO_INITDB_DATABASE=library_management
    env_file:
      - .env.dev
    networks:
      - app-network

  backend:
    container_name: backend
    build:
      context: ./server
      target: development
    ports:
      - '8080:8080' # Backend runs on 8080
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongo
    env_file:
      - .env.dev
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network
    command: sh -c "npm run dev & sleep 10 && npm run seed"

  frontend:
    container_name: frontend
    build:
      context: ./client
      target: development # Use the development stage from client Dockerfile
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=3000 # <--- Changed this from 8080 to 3000
    ports:
      - '3000:3000' # Host port 3000 maps to container port 3000
    volumes:
      - ./client:/app # Mount the client directory for hot-reloading
      - /app/node_modules # Use node_modules from within the container
    depends_on:
      - backend
    networks:
      - app-network
    command: npm start

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
