# Use the official k6 image as the base
FROM grafana/k6:latest

# Set the working directory inside the container
WORKDIR /home/k6

# Copy the performance test script into the container
COPY performance-test.js .